language: java
git:
  depth: 3
sudo: required
services:
  - docker

before_install:
- pwd
- docker build -t zulu-mvn-git .

script: docker run zulu-mvn-git -v /jHiccup jHiccup /bin/sh -c "mvn -f /jHiccup/pom.xml test"