language: java
git:
  depth: 3
sudo: required
services:
  - docker

before_install:
- pwd
- docker build -t zulu-mvn-git .

script: 
- pwd
- docker run -v `pwd`:/jHiccup zulu-mvn-git /bin/sh -c "ls /jHiccup; mvn -f /jHiccup/pom.xml test"